configmap:
  data:
    com.liferay.portal.instances.internal.configuration.PortalInstancesConfiguration-able.dxp.localtest.me.config: |
      active=B"true"
      maxUsers=I"0"
      mx="able.dxp.localtest.me"
      siteInitializerKey="blank-site-initializer"
      virtualHostname="able.dxp.localtest.me"
      adminScreenName="able"
      adminEmailAddress="able@able.dxp.localtest.me"
      adminFirstName="able"
      adminMiddleName="able"
      adminLastName="able"
      addDefaultAdminUser=B"true"
    com.liferay.portal.instances.internal.configuration.PortalInstancesConfiguration-baker.dxp.localtest.me.config: |
      active=B"true"
      maxUsers=I"0"
      mx="baker.dxp.localtest.me"
      siteInitializerKey="blank-site-initializer"
      virtualHostname="baker.dxp.localtest.me"
      adminScreenName="baker"
      adminEmailAddress="baker@baker.dxp.localtest.me"
      adminFirstName="baker"
      adminMiddleName="baker"
      adminLastName="baker"
      addDefaultAdminUser=B"true"
customVolumeMounts:
   x-saas-testbed:
     - mountPath: /opt/liferay/osgi/configs/com.liferay.portal.instances.internal.configuration.PortalInstancesConfiguration~able.dxp.localtest.me.config
       name: liferay-configmap
       subPath: com.liferay.portal.instances.internal.configuration.PortalInstancesConfiguration-able.dxp.localtest.me.config
     - mountPath: /opt/liferay/osgi/configs/com.liferay.portal.instances.internal.configuration.PortalInstancesConfiguration~baker.dxp.localtest.me.config
       name: liferay-configmap
       subPath: com.liferay.portal.instances.internal.configuration.PortalInstancesConfiguration-baker.dxp.localtest.me.config
image:
  #tag: 2025.q1.17-lts
  tag: 2025.q2.4
  #tag: 7.4.13.nightly
portalProperties: |
  include-and-override=portal-developer.properties
  company.default.virtual.host.mail.domain=main.dxp.localtest.me
  company.default.virtual.host.name=main.dxp.localtest.me
  company.default.web.id=main.dxp.localtest.me
  login.dialog.disabled=true
  passwords.default.policy.change.required=false
  web.server.display.node=true
  web.server.protocol=http
#  virtual.hosts.strict.access=false
replicaCount: 2
resources:
  limits:
    cpu: 8000m
    memory: 16Gi
  requests:
    cpu: 4000m
    memory: 12Gi
securityContext:
  readOnlyRootFilesystem: false
livenessProbe:
    timeoutSeconds: 600
