customInitContainers:
  x-patching:
    - containerTemplate: |
        - command:
          - bash
          - -c
          - |
            if [ -d /mnt/local/patching/ ]
            then
              mkdir -p /temp/liferay/patching
              cp -fv /mnt/local/patching/*.zip /temp/liferay/patching
            fi
          image: {{ printf "%s:%s" .image.repository (.image.tag | toString) }}
          imagePullPolicy: {{ .image.pullPolicy }}
          name: osgimodules-init-container
          volumeMounts:
          - mountPath: /temp
            name: liferay-persistent-volume
          - mountPath: /mnt/local
            name: mount-local
customVolumeMounts:
  x-patching:
    - mountPath: /etc/liferay/mount/patching
      name: liferay-persistent-volume
      subPath: liferay/patching

